<a href="https://colab.research.google.com/github/prd-dahal/Dive-Deep-Into-Deep-Learning/blob/master/Dive_Deep_Into_Deep_Learning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import dependencies 
import numpy as np

In [ ]:
# l1 loss 
def l_one_loss(y,y_bar):
    return np.sum(abs(y-y_bar))


#l2 loss 
def l_two_loss(y,y_bar):
  return np.sum((y-y_bar)**2)



**Data Manipulation**


In [68]:
!pip install mxnet

from mxnet import np, npx
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [50]:
x.shape


(12,)

In [7]:
x.size

12

In [10]:
X= x.reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
x.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
 np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
np.random.normal(0,1,size=(3,4))

array([[ 1.31593511,  0.24425028, -0.67601859,  0.4109992 ],
       [ 0.17370989,  0.2535232 , -1.26774693,  1.23403455],
       [-1.2132296 , -1.00151984, -1.84401594,  2.07923729]])

In [24]:
x = np.array([1,2,4,8])
y = np.array([2,2,2,2])
x+y, x-y,x*y,x/y,x**y

(array([ 3,  4,  6, 10]),
 array([-1,  0,  2,  6]),
 array([ 2,  4,  8, 16]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1,  4, 16, 64]))

In [26]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 5.45981500e+01, 2.98095799e+03])

In [33]:
X = np.arange(12).reshape(3,4)
Y = np.array([[2,1,3,4],[1,2,3,4],[4,3,2,1]])
np.concatenate([X,Y], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 2,  1,  3,  4],
       [ 1,  2,  3,  4],
       [ 4,  3,  2,  1]])

In [35]:
X ==Y

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

Saving Memory

In [39]:
before = id(Y)
before
Y = Y + X
id(Y) == before

False

In [41]:
Y = 3
X = 2 
Y = Y+X
print(Y)

5


In [48]:
Z = np.zeros_like(Y)
print('id(Z):', id(Z))
X+= Y
print('id(Z):', id(Z))


id(Z): 140525476883552
id(Z): 140525476883552


In [60]:
import os
print(os.listdir('/content/sample_data'))


def mkdir_if_not_exist(path):
  if not isinstance(path, str):
    path = os.path.join(*path)
  if not os.path.exists(path):
    os.makedirs(path)
  

['anscombe.json', 'README.md', 'california_housing_train.csv', 'mnist_train_small.csv', 'mnist_test.csv', 'california_housing_test.csv']


In [66]:
data_file = '/content/data/house_tiny.csv'

mkdir_if_not_exist('/content/data')

with open(data_file, 'w') as f:
  f.write('NUm Rooms, Alley, Price \n')
  f.write('NA, Pave, 127500\n')
  f.write('2,NA,106000\n')
  f.write('2,NA,106000\n')
  f.write('4,NA,178100\n')
  f.write('NA,NA,140000\n')


In [67]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NUm Rooms  Alley   Price 
0        NaN   Pave   127500
1        2.0    NaN   106000
2        2.0    NaN   106000
3        4.0    NaN   178100
4        NaN    NaN   140000


**Linear Algebra**


In [73]:
A = np.array([[2,3],
     [4,5]])
print(A.sum(axis =0, keepdims=True))

[[6. 8.]]


In [81]:
from IPython import display
from mxnet import np, npx
npx.set_np()

def f(x):
    return 3*x**2 -4*x

def numerical_lim(f,x,h):
  return (f(x+h)-f(x))/h

h = 0.1
for i in range(5):
  print("h = {}, numercial limit ={}".format(h, numerical_lim(f,1,h)))
  h *=0.1

h = 0.1, numercial limit =2.3000000000000043
h = 0.010000000000000002, numercial limit =2.029999999999976
h = 0.0010000000000000002, numercial limit =2.0029999999993104
h = 0.00010000000000000003, numercial limit =2.000299999997956
h = 1.0000000000000004e-05, numercial limit =2.0000300000155837
